#!/usr/bin/env python3
"""Generate dependency-graph.md from each repo's sml.pkg require{} block.

Reads `sml.pkg` manifests for the harvested ecosystem repos (from a local repos
root, e.g. the parent directory holding all the sml-* checkouts) and renders a
Mermaid graph of intra-ecosystem dependencies.

The manifest parser (`parse_pkg`) is pure and unit-tested. Repos whose manifest
is missing are simply skipped (reported in a footnote).
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data"
DEFAULT_ECOSYSTEM = DATA / "ecosystem.generated.json"
DEFAULT_OUTPUT = ROOT / "dependency-graph.md"
DEFAULT_REPOS_ROOT = ROOT.parent

ORG_PREFIX = "github.com/sjqtentacles/"

_PACKAGE_RE = re.compile(r"^\s*package\s+(\S+)", re.MULTILINE)
_REQUIRE_BLOCK_RE = re.compile(r"require\s*\{([^}]*)\}", re.DOTALL)


def parse_pkg(text: str) -> tuple[str | None, list[str]]:
    """Parse an sml.pkg manifest into (package_path, [require_paths]) (pure)."""
    pkg_match = _PACKAGE_RE.search(text)
    package = pkg_match.group(1) if pkg_match else None

    requires: list[str] = []
    block = _REQUIRE_BLOCK_RE.search(text)
    if block:
        for line in block.group(1).splitlines():
            # Strip inline version pins / comments; keep the package path token.
            token = line.strip().split()[0] if line.strip() else ""
            if token and not token.startswith("#"):
                requires.append(token)
    return package, requires


def _short(path: str) -> str | None:
    """Reduce a full package path to the bare repo name if it is in-org."""
    if path.startswith(ORG_PREFIX):
        return path[len(ORG_PREFIX):]
    return None


def _read_pkg_local(name: str, repos_root: Path) -> str | None:
    pkg_file = repos_root / name / "sml.pkg"
    if pkg_file.exists():
        return pkg_file.read_text()
    return None


def _read_pkg_gh(name: str) -> str | None:
    """Fetch sml.pkg raw content for an org repo via gh (impure: network)."""
    import subprocess

    proc = subprocess.run(
        [
            "gh",
            "api",
            f"repos/sjqtentacles/{name}/contents/sml.pkg",
            "-H",
            "Accept: application/vnd.github.raw+json",
        ],
        capture_output=True,
        text=True,
    )
    if proc.returncode != 0:
        return None
    return proc.stdout


def build_edges(
    repo_names: list[str], repos_root: Path, use_gh: bool = False
) -> tuple[list[tuple[str, str]], list[str]]:
    """Return (edges, missing) where edges are (dependent, dependency) names."""
    known = set(repo_names)
    edges: list[tuple[str, str]] = []
    missing: list[str] = []
    for name in sorted(repo_names):
        text = _read_pkg_gh(name) if use_gh else _read_pkg_local(name, repos_root)
        if text is None:
            missing.append(name)
            continue
        _package, requires = parse_pkg(text)
        for req in requires:
            dep = _short(req)
            if dep and dep in known and dep != name:
                edges.append((name, dep))
    # Deterministic ordering.
    edges = sorted(set(edges))
    return edges, missing


def render(edges: list[tuple[str, str]], total: int, missing: list[str]) -> str:
    lines = [
        "# Dependency graph",
        "",
        "Intra-ecosystem dependencies derived from each repo's `sml.pkg` "
        "`require {}` block. Generated by `scripts/depgraph.py`; do not edit "
        "by hand.",
        "",
        f"{len(edges)} edges across {total} libraries.",
        "",
        "```mermaid",
        "graph LR",
    ]
    for dependent, dependency in edges:
        a = dependent.replace("-", "_")
        b = dependency.replace("-", "_")
        lines.append(f"  {a}[{dependent}] --> {b}[{dependency}]")
    lines.append("```")
    if missing:
        lines.append("")
        lines.append(
            f"> Note: {len(missing)} repo(s) had no readable `sml.pkg` and were "
            "skipped: " + ", ".join(f"`{m}`" for m in missing) + "."
        )
    return "\n".join(lines).rstrip("\n") + "\n"


def main(argv: list[str] | None = None) -> int:
    import json

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--ecosystem", type=Path, default=DEFAULT_ECOSYSTEM)
    parser.add_argument("--repos-root", type=Path, default=DEFAULT_REPOS_ROOT)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument(
        "--gh",
        action="store_true",
        help="Fetch each sml.pkg via gh api instead of a local repos root.",
    )
    args = parser.parse_args(argv)

    eco = json.loads(args.ecosystem.read_text())
    names = [r["name"] for r in eco["repos"]]
    edges, missing = build_edges(names, args.repos_root, use_gh=args.gh)
    args.output.write_text(render(edges, len(names), missing))
    print(f"Wrote {len(edges)} edges to {args.output} ({len(missing)} skipped)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
